# Generated by Django 4.2 on 2024-10-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumento',
            old_name='nickname',
            new_name='Familia',
        ),
        migrations.RenameField(
            model_name='instrumento',
            old_name='fullname',
            new_name='Nombre_Instrumento',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='age',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='is_active',
        ),
    ]
